### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by DeadNumbers** [Neohapsis/bbqsql#51]
>$ sudo pip install bbqsql  
Collecting bbqsql
  Using cached BBQSQL-1.2.tar.gz
Collecting gevent (from bbqsql)
  Using cached gevent-1.0.1.tar.gz
Collecting requests<1.0 (from bbqsql)
  Using cached requests-0.14.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-t6900f9w/requests/setup.py", line 6, in <module>
        import requests
      File "/tmp/pip-build-t6900f9w/requests/requests/__init__.py", line 52, in <module>
        from . import utils
      File "/tmp/pip-build-t6900f9w/requests/requests/utils.py", line 22, in <module>
        from .compat import parse_http_list as _parse_list_header
      File "/tmp/pip-build-t6900f9w/requests/requests/compat.py", line 112, in <module>
        from .packages import chardet2 as chardet
    ImportError: cannot import name 'chardet2'
    
    ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-t6900f9w/requests

simple `import chardet`
topical for python 3

**Comment by wh1t3h47** [comment]
<pre><font color="#EC0101"><b>error</b></font>: <b>subprocess-exited-with-error</b>
  
  <font color="#D41919">×</font> <font color="#5EBDAB">python setup.py egg_info</font> did not run successfully.
  <font color="#D41919">│</font> exit code: <font color="#05A1F7"><b>1</b></font>
  <font color="#D41919">╰─&gt;</font> <font color="#D41919">[12 lines of output]</font>
  <font color="#D41919">   </font> Traceback (most recent call last):
  <font color="#D41919">   </font>   File &quot;&lt;string&gt;&quot;, line 2, in &lt;module&gt;
  <font color="#D41919">   </font>   File &quot;&lt;pip-setuptools-caller&gt;&quot;, line 34, in &lt;module&gt;
  <font color="#D41919">   </font>   File &quot;/tmp/pip-install-pptvyyq5/requests_8737078e6add4fce8b9ee0c5e2c40824/setup.py&quot;, line 6, in &lt;module&gt;
  <font color="#D41919">   </font>     import requests
  <font color="#D41919">   </font>   File &quot;/tmp/pip-install-pptvyyq5/requests_8737078e6add4fce8b9ee0c5e2c40824/requests/__init__.py&quot;, line 52, in &lt;module&gt;
  <font color="#D41919">   </font>     from . import utils
  <font color="#D41919">   </font>   File &quot;/tmp/pip-install-pptvyyq5/requests_8737078e6add4fce8b9ee0c5e2c40824/requests/utils.py&quot;, line 22, in &lt;module&gt;
  <font color="#D41919">   </font>     from .compat import parse_http_list as _parse_list_header
  <font color="#D41919">   </font>   File &quot;/tmp/pip-install-pptvyyq5/requests_8737078e6add4fce8b9ee0c5e2c40824/requests/compat.py&quot;, line 112, in &lt;module&gt;
  <font color="#D41919">   </font>     from .packages import chardet2 as chardet
  <font color="#D41919">   </font> ImportError: cannot import name &apos;chardet2&apos; from &apos;requests.packages&apos; (/tmp/pip-install-pptvyyq5/requests_8737078e6add4fce8b9ee0c5e2c40824/requests/packages/__init__.py)
  <font color="#D41919">   </font> <font color="#D41919">[end of output]</font>
  
  <font color="#962AC3"><b>note</b></font>: This error originates from a subprocess, and is likely not a problem with pip.
<font color="#EC0101"><b>error</b></font>: <b>metadata-generation-failed</b>

<font color="#D41919">×</font> Encountered error while generating package metadata.
<font color="#D41919">╰─&gt;</font> See above for output.

<font color="#962AC3"><b>note</b></font>: This is an issue with the package mentioned above, not pip.
<font color="#05A1F7"><b>hint</b></font>: See above for details.
</pre>

**Comment by wh1t3h47** [comment]
This issue still happens when installing bbqsql with kali linux on pip3
