### ISSUE TITLE
BBQSQL crash regardless of config

### ISSUE THREAD

**Issue by braimee** [Neohapsis/bbqsql#54]
Hi there,

I'm running a fresh Kali rolling box with the latest updates.  I watched the video (https://www.youtube.com/watch?v=I4XRnuAA-aA) and am attempting some tests in my own network, but no matter what values I feed BBQSL, it bombs with:

> Traceback (most recent call last):
>   File "/usr/bin/bbqsql", line 16, in <module>
>     bbqMenu()
>   File "/usr/lib/python2.7/dist-packages/bbqsql/menu/bbq_menu.py", line 182, in **init**
>     bbq = bbqsql.BlindSQLi(**attack_config)
>   File "/usr/lib/python2.7/dist-packages/bbqsql/lib/api.py", line 128, in **init**
>     self.requester = requester_type(comparison_attr=comparison_attr, *_kwargs)
>   File "/usr/lib/python2.7/dist-packages/bbqsql/lib/requester.py", line 122, in **init**
>     self.session = requests.session(_args,**kwargs)
> TypeError: session() takes no arguments (2 given)

Seems like it might be a system config issue rather than something with the tool?  Not sure.  Any ideas?

Thanks,
Brian

**Comment by braimee** [comment]
Any help w/this please?

**Comment by discoveredf** [comment]
After upgrade my crash gone. But i am getting 
The response values for true and false are overlapping. Check your configuration.
here are the cases we have collected:
{'false': {'case': 'false', 'rval': False, 'values': [19358], 'stddev': 0.0, 'mean': 19358.0}, 'true': {'case': 'true', 'rval': True, 'values': [19358, 19358, 19358, 19358, 19358], 'stddev': 0.0, 'mean': 19358.0}}

**Comment by braimee** [comment]
Closing.
